from . import res_config_settings
from . import sgw_control_panel
from . import sgw_ip_address
from . import sgw_operating_system
from . import sgw_partner
from . import sgw_period
from . import sgw_product
from . import sgw_reminder
from . import sgw_sale_order
from . import sgw_sale_order_line
from . import sgw_server
from . import sgw_service
from . import sgw_whois_query
